# Generated by Django 4.1.4 on 2022-12-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default=False, max_length=255)),
                ('lastname', models.CharField(default=False, max_length=255)),
                ('address', models.CharField(default=False, max_length=255)),
                ('number', models.IntegerField(default=False)),
                ('adhaarcard', models.IntegerField(default=False)),
                ('hotel_Main_Img', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
